---

  - hosts: all
    sudo: yes

    tasks:

      - name: Install kernel utils
        yum: name=yum-utils state=latest

      - name: Clean kernels
        shell: package-cleanup --oldkernels --count=1 -y
