---

  - hosts: all
    sudo: yes

    tasks:

      - name: Install required libraries
        yum: name={{ item }}  state=absent
        with_items:
          - gcc
          - cpp
          - kernel-devel
          - kernel-headers
          - perl

      - name: Remove any extant jars
        file: name="{{ item }}" state=absent
        with_items:
          - "~/VBoxGuestAdditions_*.iso"
          - "/tmp/chef*rpm"
          - "/var/cache/yum/*"
          - "/etc/udev/rules.d/70-persistent-net.rules"
