---

  - hosts: all
    sudo: yes

    tasks:

      - name: install epel-release
        yum: name=epel-release update_cache=yes state=latest
        register: epel

      - debug: msg="{{epel.results}}"
        when: debug_yum is defined

      - name: Update system with yum
        yum: name=*  state=latest update_cache=yes
        register: update
        ignore_errors: yes

      - debug: msg="{{update.results}}"
        when: debug_yum is defined
