---

  - hosts: all
    sudo: yes

    tasks:

      - name: install epel-release
        yum: name=epel-release update_cache=yes state=latest
      
      - name: Update system with yum
        yum: name=*  state=latest update_cache=yes
        ignore_errors: yes
