---

  - hosts: all
    sudo: yes

    tasks:

      - name: Install required libraries
        yum: name={{ item }}  state=latest
        with_items:
          - bzip2
          - gcc
          - make
          - perl
          - kernel-devel
          - kernel-headers

      - name: Create folder
        file: path=/tmp/vbox state=directory

      - name: Get Virtualbox version
        shell: cat /home/vagrant/.vbox_version
        register: vagrant_virtualbox_version

      - name: Mount Guest Additions
        shell: mount -o loop /home/vagrant/VBoxGuestAdditions_{{ item }}.iso /tmp/vbox
        with_items: vagrant_virtualbox_version.stdout_lines

      - name: Run Guest Additions
        shell: sh /tmp/vbox/VBoxLinuxAdditions.run
        ignore_errors: yes

      - name: Unmount Guest Additions
        shell: umount /tmp/vbox

      - name: Delete folder
        file: path=/tmp/vbox state=absent

      - name: Delete files
        file: path=/home/vagrant/*.iso state=absent

      - name: Remove required libraries
        yum: name={{ item }}  state=absent
        with_items:
          - bzip2
          - gcc
          - make
          - perl
          - kernel-devel
          - kernel-headers
